using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using log4net;
using Azavea.NijPredictivePolicing.Test.Helpers;
using System.IO;
using Azavea.NijPredictivePolicing.AcsDataImporter;

namespace Azavea.NijPredictivePolicing.Test
{
    [TestFixture]
    public class IntegrationTests
    {
        private static ILog _log = null;

        /// <summary>
        /// Place to dump files generated by tests
        /// </summary>
        protected const string OutputDir = "output\\";

        [TestFixtureSetUp]
        public void Init()
        {
            _log = LogHelpers.ResetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

            if (!Directory.Exists(OutputDir))
                Directory.CreateDirectory(OutputDir);
        }

        [Test]
        public void FullImportTest()
        {
            

            var myVariablesStr = @"
B01001001,TOTALPOP
B01001002,TOTALMALE
B01001026,TOTALFEMALE
";
            File.WriteAllText("myVariablesFile.txt", myVariablesStr);

            //string jobName = DateTime.Now.ToShortDateString();


            var args = new string[] {
                "-s",
                "Wyoming",
                "-e",
                "150",
                "-v",
                "myVariablesFile.txt",
                "-jobName",
                "Test01",
                "–exportToShape"
            };

            _log.Debug("Starting Sample Import / Export");
            Program.Main(args);
            

            Assert.IsTrue(File.Exists("Test01.shp"), "Shapefile not generated!");
        }






    }
}
