/*
  Copyright (c) 2011 Azavea, Inc.
 
  This file is part of _SOLUTIONNAME_.

  _SOLUTIONNAME_ is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  _SOLUTIONNAME_ is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with _SOLUTIONNAME_.  If not, see <http://www.gnu.org/licenses/>.
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using log4net;
using System.Net;
using System.IO;
using Azavea.NijPredictivePolicing.Common;
using Azavea.NijPredictivePolicing.Test.Helpers;
using Azavea.NijPredictivePolicing.AcsImporterLibrary;
using System.Data;
using Azavea.NijPredictivePolicing.AcsImporterLibrary.Transfer;
using Azavea.NijPredictivePolicing.AcsImporterLibrary.FileFormats;

namespace Azavea.NijPredictivePolicing.Test.AcsImporterLibrary
{
    [TestFixture]
    public class ShapefileHelperTests
    {
        /// <summary>
        /// Place to dump files generated by tests
        /// </summary>
        protected const string OutputDir = "output\\";

        private static ILog _log = null;



        [TestFixtureSetUp]
        public void Init()
        {
            _log = LogHelpers.ResetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

            if (!Directory.Exists(OutputDir))
                Directory.CreateDirectory(OutputDir);
        }

        [Test]
        public void ForbiddenNames()
        {
            Assert.AreEqual(ShapefileHelper.IsForbiddenShapefileName(""), false);
            Assert.AreEqual(ShapefileHelper.IsForbiddenShapefileName(""), false);
            
            Assert.AreEqual(ShapefileHelper.IsForbiddenShapefileName("bg00_d00.shp"), true);
            Assert.AreEqual(ShapefileHelper.IsForbiddenShapefileName("tr99_d00"), true);
            Assert.AreEqual(ShapefileHelper.IsForbiddenShapefileName("cs55_d00.shp"), true);
            Assert.AreEqual(ShapefileHelper.IsForbiddenShapefileName("z327_d00"), true);
            Assert.AreEqual(ShapefileHelper.IsForbiddenShapefileName("zt00_d00.shp"), true);
            Assert.AreEqual(ShapefileHelper.IsForbiddenShapefileName("vt00_d00"), true);
            Assert.AreEqual(ShapefileHelper.IsForbiddenShapefileName("co00_d00.shp"), true);
            Assert.AreEqual(ShapefileHelper.IsForbiddenShapefileName("co00_d00"), true);

            Assert.AreEqual(ShapefileHelper.IsForbiddenShapefileName("co00_d0a_shp.zip"), false);
            Assert.AreEqual(ShapefileHelper.IsForbiddenShapefileName("co00_da0_shp.zip"), false);
            Assert.AreEqual(ShapefileHelper.IsForbiddenShapefileName("co00_daa_shp.zip"), false);
            Assert.AreEqual(ShapefileHelper.IsForbiddenShapefileName("co00_d00_shp.zip"), false);
        }

    }
}
